### ISSUE TITLE
Docker compose not working

### ISSUE THREAD

**Issue by gidsi** [SpaceApi/provisioning#13]
```
# docker-compose pull
WARNING: Dependency conflict: an older version of the 'docker-py' package may be polluting the namespace. If you're experiencing crashes, run the following command to remedy the issue:
pip uninstall docker-py; pip uninstall docker; pip install docker
Pulling matterbridge (42wim/matterbridge:latest)...
Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 68, in main
    command()
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 121, in perform_command
    handler(command, command_options)
  File "/usr/local/lib/python2.7/dist-packages/compose/cli/main.py", line 653, in pull
    silent=options.get('--quiet'),
  File "/usr/local/lib/python2.7/dist-packages/compose/project.py", line 512, in pull
    service.pull(ignore_pull_failures, silent=silent)
  File "/usr/local/lib/python2.7/dist-packages/compose/service.py", line 1024, in pull
    output = self.client.pull(repo, tag=tag, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/image.py", line 381, in pull
    header = auth.get_config_header(self, registry)
AttributeError: 'module' object has no attribute 'get_config_header'
```

Running
```
pip uninstall docker-py; pip uninstall docker; pip install docker
```
fixes the issue

**Comment by rnestler** [comment]
What does `docker-py` do anyway?

**Comment by gidsi** [comment]
Seems like to be a requirement for ansibles docker_container and docker_image (which we currently don't use), so i would say lets remove it and we are good.

**Comment by dbrgn** [comment]
> Seems like to be a requirement for ansibles docker_container and docker_image

Last update was late 2016. Probably `docker-py` was superceded by the `docker` package.

Yeah, let's remove it in the `docker` role. If everything still works fine, we're done.

**Comment by dbrgn** [comment]
Ah, we actually installed docker-py ourselves:

```
TASK [docker : Install docker-py and docker-compose.] *****************************************
changed: [katharina.chaospott.de] => (item=docker-py)
changed: [katharina.chaospott.de] => (item=docker-compose)
```

That used to be a requirements for docker-compose, but apparently that's now `docker`.

**Comment by dbrgn** [comment]
Committed directly to master since it's a trivial change based on consensus :)

**Comment by rnestler** [comment]
You did not uninstall docker-py in your change...

**Comment by dbrgn** [comment]
> You did not uninstall docker-py in your change...

No, but I removed it manually and removed the install command. Results in the same thing, if we reinstall the server, it won't be installed.
